apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaicai-frontend
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: VaicaiFrontend
    repoURL: 'https://github.com/JoaoEler/VaicaiSorvetes'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: core
      kind: Service
      jsonPointers:
        - /spec/clusterIP
