apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: nodejs
          image: jgemendes/vaicai-backend:v1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3333