apiVersion: v1
kind: Service
metadata:
  name: nodejs
spec:
  type: NodePort
  selector:
    app: nodejs
  ports:
    - port: 3333
      protocol: TCP
      targetPort: 3333
      nodePort: 3333