name: Build Step

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.20.0]

    steps:
      - uses: actions/checkout@v3
      - name: Set working directory
        run: cd VaicaiFrontend
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          always-auth: false
          check-latest: false
          token: ${{ secrets.GITHUB_TOKEN }}
          registry-url: 'https://registry.npmjs.org/'
          scope: '.'
          working-directory: VaicaiFrontend
      - name: Install dependencies
        run: npm install
        working-directory: VaicaiFrontend
      - name: Build project
        run: npm run build --if-present
        working-directory: VaicaiFrontend

  test-stage:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Running Tests
        uses: actions/checkout@v3
      - run: echo "running"

  update-manifest-stage:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          repository: JoaoEler/VaicaiSorvetes
          ref: 'master'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Git Config
        run: |
          git config --global user.email "jgelermendes@gmail.com"
          git config --global user.name "JoaoEler"
      - name: Update Image in Deployment Manifest
        run: |
          sed -i "s#${{ github.actor }}.*#${{ github.actor }}/VaicaiSorvetes:${{ github.sha }}#g" deployment.yaml
          git add -A
          git commit -am "Update image for - ${{ github.sha }}"
      - name: Push Changes to Remote Repository
        run: git push origin master