name: Build and Deploy

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.20.0]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Change to VaicaiFrontend directory
        run: cd VaicaiFrontend

      - name: Delete package-lock.json
        run: rm -f VaicaiFrontend/package-lock.json

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install
        working-directory: VaicaiFrontend

      - name: Build project
        run: npm run build --if-present
        working-directory: VaicaiFrontend

  test-stage:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Running Tests
        run: echo "Running tests"